name: Devlake Devel

on:
  push:
    branches:
      - main
    paths:
      - devlake-devel/**
      - build-and-push.sh

jobs:
  devlake-devel:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: build and push image
        run: |
          sh build-and-push.sh devlake-devel linux/amd64,linux/arm64/v8 latest
